# -*- coding: utf-8 -*-
"""Tugas Praktikum Modul 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LQTC78Zsu_olJnQNMRFfYfGcMjuRa5lt
"""

#Tugas Praktikum Modul 2

def buat_papan(lebar):
    return [[' ' for a in range(lebar)]
            for b in range(lebar)]

import random

def generate_posisi(lebar):
    posisi = [(0, 0), (lebar - 1, lebar - 1)]
    random.shuffle(posisi)
    return posisi[0], posisi[1]

def update_posisi_bidak(perintah, posisi_bidak, lebar):
    baris, kolom = posisi_bidak
    if perintah == 'w' and baris > 0:
        return (baris - 1, kolom)
    elif perintah == 'a' and kolom > 0:
        return (baris, kolom - 1)
    elif perintah == 's' and baris < lebar - 1:
        return (baris + 1, kolom)
    elif perintah == 'd' and kolom < lebar - 1:
        return (baris, kolom + 1)
    else:
        return (baris, kolom)

def kondisi_menang(bidak, goals):
    return bidak[0] == goals[0] and bidak[1] == goals[1]

def tampilkan_papan(papan, posisi_bidak, posisi_goals):
    lebar = len(papan)
    for i in range(lebar):
        for j in range(lebar):
            if (i, j) == posisi_bidak:
                print('A', end=' ')
            elif (i, j) == posisi_goals:
                print('O', end=' ')
            else:
                print('-', end=' ')
        print()

def main():
    lebar = int(input("Masukkan lebar papan: "))
    papan_permainan = buat_papan(lebar)

    for acak in range(3):
        try:
            posisi_bidak, posisi_goals = generate_posisi(lebar)
            break
        except ValueError:
            continue
    else:
        print("Gagal menghasilkan posisi awal bidak dan goals secara acak.")
        return

    print("Selamat Datang Dalam Permainan!")
    print("Simbol A adalah Bidak, Simbol O adalah Tujuan.")
    print(f"Posisi awal Bidak: {posisi_bidak}")
    print(f"Posisi Tujuan: {posisi_goals}")

    while True:
        tampilkan_papan(papan_permainan, posisi_bidak, posisi_goals)

        perintah = input("Masukkan perintah (w/a/s/d): ")
        if perintah == 'q':
            print("Permainan dihentikan.")
            break

        posisi_bidak = update_posisi_bidak(perintah, posisi_bidak, lebar)

        if kondisi_menang(posisi_bidak, posisi_goals):
            print("Selamat! Anda menang!")

if __name__ == "__main__":
    main()