# -*- coding: utf-8 -*-
"""Tugas Praktikum Modul 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X1n3UPpdf1b5jGLGDAgF7B1ui6M2n2_f
"""

# Tugas Praktikum Modul 3

movies = [
    {"title": "Avengers: Endgame", "year": 2019, "rating": 8.4, "genre": "Action"},
    {"title": "Parasite", "year": 2019, "rating": 8.6, "genre": "Drama"},
    {"title": "Nomadland", "year": 2020, "rating": 7.3, "genre": "Drama"},
    {"title": "Dune", "year": 2021, "rating": 7.9, "genre": "Sci-Fi"},
    {"title": "Spider-Man: No Way Home", "year": 2021, "rating": 7.6, "genre": "Action"},
    {"title": "The French Dispatch", "year": 2021, "rating": 7.0, "genre": "Comedy"},
    {"title": "A Quiet Place Part II", "year": 2020, "rating": 7.4, "genre": "Horror"},
    {"title": "No Time to Die", "year": 2021, "rating": 6.8, "genre": "Action"},
    {"title": "the Power of the Dog", "year": 2021, "rating": 7.3, "genre": "Drama"},
    {"title": "Eternals", "year": 2021, "rating": 6.4, "genre": "Action"},
    {"title": "The Last Duel", "year": 2021, "rating": 7.0, "genre": "Drama"},
]

# Fungsi untuk menampilkan data dari film yang dipilih
def tampilkan_data(film):
    return next((item for item in movies if item["title"] == film), "Film tidak ditemukan")

# Fungsi untuk menghtiung jumlah film berdasarkan genre
def jumlah_film_genre():
    genres = set(map(lambda x: x["genre"], movies))
    return {genre: len([x for x in movies if x["genre"] == genre]) for genre in genres}

from functools import reduce

# Fungsi menghitung rata-rata rating film berdasarkan tahun rilis
def rata2_rating_tahun():
    tahun = sorted(set(map(lambda x: x["year"], movies)))
    avg_rating = {}

    for year in tahun:
        movies_in_year = [x for x in movies if x["year"] == year]
        total_rating = reduce(lambda a, b: a + b["rating"], movies_in_year, 0)
        average_rating = total_rating / len(movies_in_year)
        avg_rating[year] = average_rating

    return avg_rating

# Fungsi mencari film dengan rating tertinggi
def film_rating_tertinggi():
    return max(movies, key=lambda x: x["rating"])

def menu():
    print("a. Tampilkan Data Film")
    print("b. Jumlah Film Berdasarkan Genre")
    print("c. Rata-Rata Rating Film Berdasarkan Tahun Rilis")
    print("d. Film Dengan Rating Tertinggi")
    print("e. Keluar")

    while True:
        pilihan = input("Masukkan pilihan Anda (a/b/c/d/e): ")
        if pilihan == "a":
            film = input("Masukkan nama film: ")
            print(tampilkan_data(film))
        elif pilihan == "b":
            print(jumlah_film_genre())
        elif pilihan == "c":
            print(rata2_rating_tahun())
        elif pilihan == "d":
            print(film_rating_tertinggi())
        elif pilihan == "e":
            break
        else:
            print("Pilihan tidak valid, silakan coba lagi.")

menu()