# -*- coding: utf-8 -*-
"""Latihan Praktikum Modul 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gIoy3tKhbxogEHIi0RDQyX8ErJ5ckjTf
"""

# Tugas Praktikum Modul 5
# Kegiatan 1

import matplotlib.pyplot as plt
import numpy as np

xpoints = np.array([1, 8])
ypoints = np.array([3, 10])

plt.plot(xpoints, ypoints)
plt.show()

# Tugas Praktikum Modul 5
# Kegiatan 2

import matplotlib.pyplot as plt
import numpy as np

xpoints = np.array([1, 8, 10])
ypoints = np.array([3, 10, 5])

plt.figure(figsize=(5, 5))
plt.plot(xpoints, ypoints, color='red')
plt.xlim([0,15])
plt.ylim([0,15])
plt.title('Percobaan 2', color='blue')
plt.show()

# Tugas Praktikum Modul 5
# Kegiatan 3

import matplotlib.pyplot as plt
import numpy as np

y1 = np.array([3, 8, 1, 10])
y2 = np.array([6, 2, 7, 11])
y3 = np.array([2, 2, 2, 2])

plt.plot(y1, label='Garis 1')
plt.plot(y2, label='Garis 2')
plt.plot(y3, label='Garis 3')

plt.title('Plot Dua Garis')
plt.xlabel('Nilai x')
plt.ylabel('Nilai y')

plt.legend()
plt.show()

# Tugas Praktikum Modul 5
# Kegiatan 4

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [3, 7, 2, 8, 5]

plt.scatter(x, y, color = 'black')
plt.plot(x, y, color='grey')
plt.show()

# Tugas Praktikum Modul 5
# Kegiatan 5

import matplotlib.pyplot as plt
from numpy.random import normal
import numpy as np
from numpy import std, mean
from scipy.stats import norm

sample = normal(loc=50, scale=5, size=1000)

plt.figure(figsize=(5,4))
plt.hist(sample, bins=10)
plt.show()

sample_mean = np.mean(sample)
sample_std = np.std(sample)
print('Mean=%.3f \nStandard Deviation=%.3f' % (sample_mean, sample_std))

dist = norm(sample_mean, sample_std)
dist

values = [value for value in range (30, 70)]
prob = [dist.pdf(value) for value in values]

plt.hist(sample, bins=10, density=True)
plt.plot(values, prob)
plt.show()