# -*- coding: utf-8 -*-
"""Tugas Praktikum Modul 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JU7F659bXtGQT2f_RNQ27OGjZUzziE66
"""

# Tugas Praktikum Modul 4

import math

def titik(x, y):
    return x, y

# Fungsi Translasi
def translasi(tx, ty):
    def transformasi(P):
        return (P[0] + tx, P[1] + ty)
    return transformasi

# Fungsi Rotasi
def rotasi(sudut):
    sudut_radian = math.radians(sudut)
    def transformasi(P):
        return (P[0] * math.cos(sudut_radian) - P[1] * math.sin(sudut_radian), P[0] * math.sin(sudut_radian) + P[1] * math.cos(sudut_radian))
    return transformasi

# Fungsi Dilatasi
def dilatasi(sx, sy):
    def transformasi(P):
        return (P[0] * sx, P[1] * sy)
    return transformasi

def persamaan_garis(p1, M):
    def hitung_konstanta():
        x1, y1 = p1
        return y1 - M * x1

    C = hitung_konstanta()
    return f"y = {M:.2f}x + {C:.2f}"

# Decorator
def transformasi_gabungan(*fungsi):
    def gabungan(P):
        for f in fungsi:
            P = f(P)
        return P
    return gabungan

# Input User
x = int(input("Masukkan koordinat x: "))
y = int(input("Masukkan koordinat y: "))
M = int(input("Masukkan gradien: "))

# Titik awal
A = titik(x, y)

# Transformasi beruntun
A_transformasi = transformasi_gabungan(translasi(2, -3), rotasi(60), dilatasi(1.5, 2))(A)

# Gradien
gradien_A = M

# Persamaan garis sebelum transformasi
pers_sebelum = persamaan_garis(A, gradien_A)

# Persamaan garis setelah transformasi
pers_setelah = persamaan_garis(A_transformasi, gradien_A)

print("Persamaan garis yang melalui titik ({}, {}) dan bergradien {}:".format(x, y, M))
print(pers_sebelum)
print("Persamaan garis baru setelah transformasi:")
print(pers_setelah)