# -*- coding: utf-8 -*-
"""Latihan Praktikum Modul 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fDfZscq86Av5YDMZkptwT-tR3w-rZb7q
"""

# Latihan Praktikum Modul 6
# Kegiatan 1

from google.colab import drive
from PIL import Image, ImageDraw, ImageFont

drive.mount('/content/drive')
gambarku = Image.open('/content/drive/My Drive/Folder Image/UnivMuhammadiyah.jpeg')

gambar = gambarku.convert("L")

draw = ImageDraw.Draw(gambar)
font = ImageFont.truetype('/content/drive/My Drive/Folder Image/font/arial.ttf', 24)
text = " Muhammad Habibulloh | 202110370311259"
text_width, text_height = draw.textbbox((0, 0), text, font=font)[2:]
text_x = (gambarku.width - text_width) // 2
text_y = 20
draw.text((text_x, text_y), text, font=font)

gambar.save("/content/drive/My Drive/Folder Image/percobaan_satu.jpeg")
gambar.show()

from google.colab import drive
from PIL import Image

drive.mount('/content/drive')

background_image = Image.open('/content/drive/My Drive/Folder Image/UnivMuhammadiyah.jpeg')
overlay_image = Image.open('/content/drive/My Drive/Folder Image/LogoUMM.jpeg')

# Mengonversi overlay image ke mode RGB
overlay_image = overlay_image.convert("RGB")

# Memperkecil ukuran gambar overlay menggunakan method resize()
# overlay_image = overlay_image.resize((50, 50))

# Tentukan/Hitung koordinat tengah untuk menempatkan overlay
x_center = (background_image.width - overlay_image.width) // 2
y_center = (background_image.height - overlay_image.height) // 2

background_image.paste(overlay_image, (x_center, y_center))
background_image.save("/content/drive/My Drive/Folder Image/percobaan_dua.jpeg")
background_image.show()

from PIL import Image, ImageEnhance
from google.colab import drive

drive.mount('/content/drive')
gambar = Image.open('/content/drive/My Drive/Folder Image/UnivMuhammadiyah.jpeg')

# Ubah tingkat kecerahan menjadi 1.5 kali lipat
enhancer = ImageEnhance.Brightness(gambar)
gambar = enhancer.enhance(1.5)

# Ubah tingkat kontras menjadi 1.2 kali lipat
enhancer = ImageEnhance.Contrast(gambar)
gambar = enhancer.enhance(1.2)

gambar.save("/content/drive/My Drive/Folder Image/brightness_contrast_image.jpg")
gambar.show()