# -*- coding: utf-8 -*-
"""Tugas Praktikum Modul 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13mKWcI-c7zSo8ouDlWXaip9Ph1beOUN2
"""

from PIL import Image, ImageDraw, ImageFont, ImageEnhance, ImageFilter
from google.colab import drive

drive.mount('/content/drive')

background_image = Image.open('/content/drive/My Drive/Folder Image/UnivMuhammadiyah.jpeg')
overlay_image = Image.open('/content/drive/My Drive/Folder Image/LogoUMM.jpeg')

# Mengubah gambar background menjadi hitam-putih (grayscale), berotasi sebesar 30 derajat, dan blur
background_image = background_image.convert("L").rotate(30).filter(ImageFilter.BLUR)

# Mengubah tingkat kecerahan gambar overlay menjadi 1.5 kali lipat dan tingkat kontras menjadi 1.9 kali lipat
enhancer = ImageEnhance.Brightness(overlay_image)
overlay_image = enhancer.enhance(1.5)
enhancer = ImageEnhance.Contrast(overlay_image)
overlay_image = enhancer.enhance(1.9)

# Resize gambar overlay sesuai kebutuhan
overlay_image = overlay_image.resize((100, 100))  # Ubah ukuran sesuai kebutuhan

# Menyisipkan gambar overlay ke dalam gambar background sehingga terlihat seperti stiker pada gambar latar belakang
x_center = (background_image.width - overlay_image.width) // 2
y_center = (background_image.height - overlay_image.height) // 2
background_image.paste(overlay_image, (x_center, y_center))

# Menambahkan teks "Informatika JOSSS!" pada gambar overlay dengan font Arial dan ukuran 24
draw = ImageDraw.Draw(background_image)
font = ImageFont.truetype('/content/drive/My Drive/Folder Image/font/arial.ttf', 24)
text = "Informatika JOSSS!"
text_width, text_height = draw.textbbox((0, 0), text, font=font)[2:]
text_x = (background_image.width - text_width) // 2
text_y = 20
draw.text((text_x, text_y), text, font=font)

background_image.save("/content/drive/My Drive/Folder Image/tugas_praktikum_enam.jpg")
background_image.show()